baseURL = "https://radish.cloud/"
publishdir                       = "docs"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
summaryLength = 180

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 网站标题


[params]
  # LoveIt 主题版本
  version = "0.2.X"
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "RadishCloud"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
  

  [params.home]
    # LoveIt 新增 | 0.2.0 RSS 文章数目
    rss = 20
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "1979646055@qq.com"
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.png"
      # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = "这是我的全新 Hugo 网站"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = "这是一份免责声明"
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false
    
    [params.social]
    GitHub = "RadishKin"
    Telegram = "radishcloud"
    Bitbucket = ""
    Weibo = "1910759497"
    Spotify = ""
    Steam = ""
    Bilibili = "5710210"
    Email = "1979646055@qq.com"
    RSS = true # LoveIt 新增 | 0.2.0

    [params.page]
      # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
      hiddenFromHomePage = false
      # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
      hiddenFromSearch = false
      # LoveIt 新增 | 0.2.0 是否使用 twemoji
      twemoji = false
      # 是否使用 lightgallery
      lightgallery = false
      # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
      ruby = true
      # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
      fraction = true
      # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
      fontawesome = true
      # 是否在文章页面显示原始 Markdown 文档链接
      linkToMarkdown = true
      # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
      rssFullText = false
      # LoveIt 新增 | 0.2.0 目录配置
      [params.page.toc]
        # 是否使用目录
        enable = true
        # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
        keepStatic = false
        # 是否使侧边目录自动折叠展开
        auto = true
      # LoveIt 新增 | 0.2.0 代码配置
      [params.page.code]
        # 是否显示代码块的复制按钮
        copy = true
        # 默认展开显示的代码行数
        maxShownLines = 10
      # LoveIt 更改 | 0.2.0 KaTeX 数学公式
      [params.page.math]
        enable = true
        # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
        blockLeftDelimiter = ""
        blockRightDelimiter = ""
        # 默认行内定界符是 $ ... $ 和 \\( ... \\)
        inlineLeftDelimiter = ""
        inlineRightDelimiter = ""
        # KaTeX 插件 copy_tex
        copyTex = true
        # KaTeX 插件 mhchem
        mhchem = true
      # LoveIt 新增 | 0.2.0 Mapbox GL JS 配置

      [params.page.share]
        enable = true
        Twitter = true
        Line = true
        Weibo = true
        Baidu = true
        Evernote = true
      
      [params.page.comment]
        enable = true
        [params.page.comment.utterances]
        enable = true
        # owner/repo
        repo = "Lairdkin/blog"
        issueTerm = "pathname"
        label = "blog_comment"
        lightTheme = "github-light"
        darkTheme = "github-dark"
      
      


  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "萝卜炖鱼丸"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = false

  


[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false


[languages]
  [languages.en]
    weight = 1
    title = "RadishKin Blog"
    languageCode = "en"
    contentDir  = "content/en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "links"
      pre = ""
      post = ""
      name = "Links"
      url = "/links/"
      title = ""
      weight = 4
    [languages.en.params.footer]

      enable = true
      # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
      custom = 'Deployed on <b><a href="//pages.github.com">GIthub Pages</a></b>，Network Turbo powered by <b><a href="//cloudflare.com">Cloudflare</b></b>'
      # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
      hugo = true
      # LoveIt 新增 | 0.2.0 是否显示版权信息
      copyright = true
      # LoveIt 新增 | 0.2.0 是否显示作者
      author = true
      # 网站创立年份
      since = 2018
      # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
      icp = ""
      # 许可协议信息 (支持 HTML 格式)
      license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  

  [languages.zh-cn]
    weight = 2
    title = "萝卜炖鱼丸"
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
     contentDir = "content/cn"
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "links"
      pre = ""
      post = ""
      name = "友情链接"
      url = "/links/"
      title = ""
      weight = 4
    [languages.zh-cn.params.footer]
      enable = true
      # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
      custom = '站点部署于<b><a href="//pages.github.com">GIthub Pages</a></b>，由<b><a href="//cloudflare.com">Cloudflare</b></b>提供加速'
      # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
      hugo = true
      # LoveIt 新增 | 0.2.0 是否显示版权信息
      copyright = true
      # LoveIt 新增 | 0.2.0 是否显示作者
      author = true
      # 网站创立年份
      since = 2018
      # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
      icp = "<a href='https://beian.miit.gov.cn/'>蒙ICP备14003205号</a>"
      # 许可协议信息 (支持 HTML 格式)
      license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  